name: Blotout Airbyte shopify source build
on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Required Tools
      run: |
        make tools.airbyte-ci.install

    - name: Ensure Docker Is Installed
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        docker --version  # Verify Docker installation

    - name: Build  Connector Docker Image
      working-directory: airbyte-integrations/connectors/source-shopify
      run: |
        airbyte-ci connectors --name=source-shopify build

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag and Push Docker Image
      run: |
        # Tag the built image to match your DockerHub naming convention
        docker tag airbyte/source-shopify:dev blotout/airbyte-source-shopify:latest

        # Push the tagged image to DockerHub
        docker push blotout/airbyte-source-shopify:latest
