name: Docker Release

on:
  release:
    types: [ "published" ]

env:
  DOCKER_TAG: |
    ${{ github.ref_name }}

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-java@v1
      with:
        java-version: '14'

    - uses: actions/setup-node@v1
      with:
        node-version: '16.13.0'
        
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      run: make build
    - name: Push Web App Docker
      run: |
        docker tag airbyte_1/webapp:dev blotout/airbyte_1-webapp:${{ env.DOCKER_TAG }}
        docker push blotout/airbyte_1-webapp:${{ env.DOCKER_TAG }}
    - name: Push Server Docker
      run: |
        docker tag airbyte_1/server:dev blotout/airbyte_1-server:${{ env.DOCKER_TAG }}
        docker push blotout/airbyte_1-server:${{ env.DOCKER_TAG }}
    - name: Push Scheduler Docker
      run: |
        docker tag airbyte_1/scheduler:dev blotout/airbyte_1-scheduler:${{ env.DOCKER_TAG }}
        docker push blotout/airbyte_1-scheduler:${{ env.DOCKER_TAG }}
    # - name: Push DB Docker
    #   run: |
    #     docker tag airbyte_1/db:dev blotout/airbyte_1-db:${{ env.DOCKER_TAG }}
    #     docker push blotout/airbyte_1-db:${{ env.DOCKER_TAG }}
    - name: Push Worker Docker
      run: |
        docker tag airbyte_1/worker:dev blotout/airbyte_1-worker:${{ env.DOCKER_TAG }}
        docker push blotout/airbyte_1-worker:${{ env.DOCKER_TAG }}
    - name: Push Temporal Docker
      run: |
        docker tag airbyte_1/temporal:dev blotout/airbyte_1-temporal:${{ env.DOCKER_TAG }}
        docker push blotout/airbyte_1-temporal:${{ env.DOCKER_TAG }}

    - run: echo "🎉 airbyte_1 App Docker Image blotout/airbyte_1-webapp:${{ env.DOCKER_TAG }}"
    - run: echo "🎉 airbyte_1 Server Docker Image blotout/airbyte_1-server:${{ env.DOCKER_TAG }}"
    - run: echo "🎉 airbyte_1 Scheduler Docker Image blotout/airbyte_1-scheduler:${{ env.DOCKER_TAG }}"
    - run: echo "🎉 airbyte_1 Worker Docker Image blotout/airbyte_1-worker:${{ env.DOCKER_TAG }}"
    - run: echo "🎉 airbyte_1 Temporal Docker Image blotout/airbyte_1-temporal:${{ env.DOCKER_TAG }}"