name: Release-Blotout Woocommerce Build and Push  Source Docker Image

on:
  release:
    types: [ "published" ]
  workflow_dispatch:  # Manually triggerable from GitHub UI

env:
  DOCKER_IMAGE: ${{ github.ref_name }}

  
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Create a branch from the tag
      run: |
        git switch -c release-${{ github.ref_name }}

    - name: Ensure branch is created if in detached HEAD
      run: |
        if [ -z "$(git symbolic-ref --short -q HEAD)" ]; then
          echo "Creating temporary branch to avoid detached HEAD..."
          git switch -c temp-branch
        fi 

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install airbyte-ci
      run: |
            make tools.airbyte-ci.install
            make tools.airbyte-ci.check
    # - name: Install Docker
    #   run: |
    #     sudo apt-get update 
    #     sudo apt-get install -y docker.io

    - name: Build Woocommerce Source Docker Image
      run: |
        cd airbyte-integrations/connectors/source-woocommerce
        pwd & ls -la
        airbyte-ci connectors --name=source-woocommerce build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker image
      run: |
        docker images
        docker tag airbyte/source-woocommerce:dev blotout/source-woocommerce:${{ env.DOCKER_TAG }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push blotout/source-woocommerce:${{ env.DOCKER_TAG }}


  output_image_tag:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Output Airbyte Server Docker Image Tag
        run: |
          echo "Docker Image Tag: blotout/source-woocommerce:${{ env.DOCKER_TAG }}"