name: Release-Blotout Shopify Build and Push Shopify Source Docker Image

on:
  release:
    types: [ "published" ]
  workflow_dispatch:  # Manually triggerable from GitHub UI

env:
  DOCKER_IMAGE: |
    blotout/source-shopify:${{ github.ref_name }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Create a branch from the tag
      run: |
        git switch -c release-${{ github.ref_name }}

    - name: Ensure branch is created if in detached HEAD
      run: |
        if [ -z "$(git symbolic-ref --short -q HEAD)" ]; then
          echo "Creating temporary branch to avoid detached HEAD..."
          git switch -c temp-branch
        fi

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install airbyte-ci
      run: |
            make tools.airbyte-ci.install
            make tools.airbyte-ci.check

    - name: Build Shopify Source Docker Image
      run: |
        cd airbyte-integrations/connectors/source-shopify
        pwd & ls -la
        airbyte-ci connectors --name=source-shopify build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker image
      run: |
        docker images
        docker tag airbyte/source-shopify:dev ${{ env.DOCKER_IMAGE }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ env.DOCKER_IMAGE }}


  output_image_tag:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Output Airbyte Server Docker Image Tag
        run: |
          echo "Docker Image Tag: ${{ env.DOCKER_IMAGE }}"
       